### ISSUE TITLE
[Question] Looking for Context propagation mechanism for Apache SkyWalking golang sdk

### ISSUE THREAD

**Issue by wu-sheng** [jtolds/gls#11]
Hi @jtolds , glad to find these cool codes. I am the original creator and current PPMC, committer of Apache SkyWalking (incubating) project: https://github.com/apache/incubator-skywalking

I am a rookie and new for golang ecosystem, and aware of building an auto-instrument(I prefer most) is possible but hard. So the first step is providing a manual instrument sdk based on SkyWalking model, like you did in [monkit-zipkin](https://github.com/spacemonkeygo/monkit-zipkin).

So I definitely look for the thread local propagation for matching our tracing context : https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/ContextManager.java#L46 I assume the **gls** library can do that? Am I right?

And also, I found your [spacemonkeygo/monkit](https://github.com/spacemonkeygo/monkit) library, but look like it is more likely based on  a pure manual context propagation. Do I get the point right?

I hope you can have time to help with our Apache project.

**Comment by jadr2ddude** [comment]
Don't use gls in production. It is more of a "Can this be done?" project than a "Should this be done?" project. Please read the "What are people saying?" part of the README for more information.

**Comment by wu-sheng** [comment]
@jadr2ddude Thanks for sharing. That also means, go trace will base on Context manual propagation, right? This is a tradition.

As that, every method need a Context interface, like opentracing-go did.

**Comment by jtolds** [comment]
that's right. blog.golang.org/context talks more about why the go folks decided to make you add an argument to every function call rather than add something useful to the language

**Comment by jtolds** [comment]
that said... some people do use gls in production. it's not go idiomatic and might make some go developers upset, but it does work reliably if you need a way to add context specific data without changing all the function signatures.

the only thing i would stress is that gls values do not follow new goroutines, which stinks for tracing. if someone starts a new subroutine in a goroutine, it loses all gls contextual information, which may be a non starter for your use case

**Comment by jtolds** [comment]
(i definitely have used gls in production for logging, tracing, and other debugging concerns to great success. regardless of the "what other people are saying" label it's always important to be pragmatic and realize others' knee jerk reactions might not be especially applicable to your situation)

**Comment by wu-sheng** [comment]
Threadlocal in java also cant deal with sub thread, that is where manual propagation happens.

**Comment by wu-sheng** [comment]
I hope I can provide both ways, gls based and OpenTracing compatible. But I am very new to golang, hope can do that.
