### ISSUE TITLE
Not working at Go tip

### ISSUE THREAD

**Issue by GinjaNinja32** [jtolds/gls#12]
gls currently does not work at Go tip - it appears to have broken somewhere between 1.11.2 and golang/go@78c0e1f81d4052f8ca5a50e4e7c5bb35ddec6519.

This means that the [goconvey package](https://github.com/smartystreets/goconvey) doesn't work any more, since it relies on gls for context tracking.

Test code:
```
package main

import (
	"fmt"
	"runtime"

	"github.com/jtolds/gls"
)

func main() {
	fmt.Printf("Go version: %s\n", runtime.Version())
	manager := gls.NewContextManager()

	manager.SetValues(gls.Values{
		"foo": 1,
	}, func() {
		foo, ok := manager.GetValue("foo")
		fmt.Printf("foo, ok = %+v, %t\n", foo, ok)
	})
}
```

Output on recent versions:
```
Go version: go1.11.1
foo, ok = 1, true
```
```
Go version: go1.11.2
foo, ok = 1, true
```
```
Go version: devel +78c0e1f Fri Nov 9 19:57:57 2018 +0000
foo, ok = <nil>, false
```

**Comment by GinjaNinja32** [comment]
Bisected to golang/go@13baf4b2cd34dfb41c570e35b48ec287713f4d7f.

**Comment by jtolds** [comment]
nice! better inlining! okay I'll fix

**Comment by jtolio** [comment]
fixed
