### ISSUE TITLE
SetValues breaks in Go 1.12

### ISSUE THREAD

**Issue by wwwjfy** [jtolds/gls#14]
A simple example below. `GetValue` should return 0, true, but in Go 1.12, it returns 0, false.

```go
package main

import (
	"fmt"

	"github.com/jtolds/gls"
)

func main() {
	mgr := gls.NewContextManager()
	mgr.SetValues(gls.Values{"node": 1}, func() {
		fmt.Println(mgr.GetValue("node"))
	})
}
```

**Comment by wwwjfy** [comment]
Possible cause: https://golang.org/doc/go1.12#compiler

`More functions are now eligible for inlining by default, including functions that do nothing but call another function.`

**Comment by tietang** [comment]
😃😄😝 you can update it and try , may be fix it.

**Comment by wwwjfy** [comment]
I guess I find the reason. The last commit with `noinline` should fix this, but it's inappropriately tagged as `4.20`.
I tried to manually apply the commit and it returns true now. @jtolds could you help to tag it as `4.2.2`?

**Comment by jtolio** [comment]
4.20 was supposed to be newer than 4.2.1, but i forgot semantic versioning requires three numbers. added a tag for 4.20.0 and it seems fixed now

**Comment by jtolio** [comment]
please reopen if not

**Comment by un000** [comment]
I don't see any tags

**Comment by wwwjfy** [comment]
https://github.com/jtolds/gls/releases
`v4.20.0` I guess the date is when the commit happened, not when the tag was generated
