### ISSUE TITLE
latest go development version breaks gls

### ISSUE THREAD

**Issue by ththvseo** [jtolds/gls#7]
see for example https://github.com/smartystreets/goconvey/issues/476
somebody said it's due to improved inlining (removing the tag frames from the call stack).

**Comment by jtolds** [comment]
Thanks for the report! Should be fixed.

**Comment by zeebo** [comment]
fyi there's a //go:noinline annotation you can put on a function to have it not be inlined

**Comment by jtolds** [comment]
lol that would have been better

**Comment by jtolds** [comment]
looks like //go:noinline is deliberately not documented: https://github.com/golang/go/issues/18049
makes me nervous enough to leave this as-is. the only way this solution could fail is if the compiler changes to do enough analysis to decide both that preventInlining() isn't exported and isn't called within the package, and as a result is worth eliminating even though reflection might be able to call it.
