### ISSUE TITLE
Please make a new release/tag with latest fix for tip

### ISSUE THREAD

**Issue by AlekSi** [jtolds/gls#8]

**Comment by jtolds** [comment]
I'm not sure I understand the goal here. Would it be alright if you provided more reasoning for what you're looking for? This package isn't using gopkg.in or something that uses releases and tags. Since this is an unversioned go-gettable package, don't new users always get the latest commit?

**Comment by jtolds** [comment]
For context, no releases or tags exist currently.

**Comment by AlekSi** [comment]
That's not true: https://github.com/jtolds/gls/releases. Any package management tools tend to treat it as the latest release.

**Comment by jtolds** [comment]
Oh, wow, okay, mega fail on my part, you are totally right, and I clearly can't be trusted with using a simple user interface. I usually use branches so when I didn't see any I didn't think to check for tags.

Okay, thank you so much for filing this issue, sorry for my unreasonable push back and lack of understanding on my own project! I've created a new tag.

**Comment by jtolds** [comment]
lol "For context, no releases or tags exist currently." Right before writing this I went to go check the Github branch dropdown, saw nothing besides master in the branch list, and moved on. :(
